[[headers]]
  for = "/*"
  [headers.values]
   X-Frame-Options= "SAMEORIGIN"
   # X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy: script-src 'self'
    Permissions-Policy: geolocation=(self "https://phoebeleiheii.netlify.app"), microphone=()
    
